#pragma once
#include <SFML/Copyright.hpp> // LICENSE AND COPYRIGHT (C) INFORMATION

////////////////////////////////////////////////////////////
// Headers
////////////////////////////////////////////////////////////
#include "SFML/Base/Traits/HasVirtualDestructor.hpp"
#include "SFML/Base/Traits/IsAggregate.hpp"
#include "SFML/Base/Traits/IsBaseOf.hpp"
#include "SFML/Base/Traits/IsConstructible.hpp"
#include "SFML/Base/Traits/IsConvertible.hpp"
#include "SFML/Base/Traits/IsCopyAssignable.hpp"
#include "SFML/Base/Traits/IsCopyConstructible.hpp"
#include "SFML/Base/Traits/IsDefaultConstructible.hpp"
#include "SFML/Base/Traits/IsEmpty.hpp"
#include "SFML/Base/Traits/IsEnum.hpp"
#include "SFML/Base/Traits/IsFloatingPoint.hpp"
#include "SFML/Base/Traits/IsMoveAssignable.hpp"
#include "SFML/Base/Traits/IsMoveConstructible.hpp"
#include "SFML/Base/Traits/IsNothrowMoveAssignable.hpp"
#include "SFML/Base/Traits/IsNothrowMoveConstructible.hpp"
#include "SFML/Base/Traits/IsReference.hpp"
#include "SFML/Base/Traits/IsRvalueReference.hpp"
#include "SFML/Base/Traits/IsSame.hpp"
#include "SFML/Base/Traits/IsStandardLayout.hpp"
#include "SFML/Base/Traits/IsTrivial.hpp"
#include "SFML/Base/Traits/IsTriviallyAssignable.hpp"
#include "SFML/Base/Traits/IsTriviallyCopyAssignable.hpp"
#include "SFML/Base/Traits/IsTriviallyCopyConstructible.hpp"
#include "SFML/Base/Traits/IsTriviallyCopyable.hpp"
#include "SFML/Base/Traits/IsTriviallyDestructible.hpp"
#include "SFML/Base/Traits/IsTriviallyMoveAssignable.hpp"
#include "SFML/Base/Traits/IsTriviallyMoveConstructible.hpp"
#include "SFML/Base/Traits/RemoveCVRef.hpp"
#include "SFML/Base/Traits/RemoveReference.hpp"
#include "SFML/Base/Traits/UnderlyingType.hpp"
