add_test( [==[[Graphics] sf::BlendMode]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-graphics.exe [==[--test-case=[Graphics] sf::BlendMode]==])
set_tests_properties( [==[[Graphics] sf::BlendMode]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Graphics] sf::CircleShape]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-graphics.exe [==[--test-case=[Graphics] sf::CircleShape]==])
set_tests_properties( [==[[Graphics] sf::CircleShape]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Graphics] sf::Color]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-graphics.exe [==[--test-case=[Graphics] sf::Color]==])
set_tests_properties( [==[[Graphics] sf::Color]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Graphics] sf::ConvexShape]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-graphics.exe [==[--test-case=[Graphics] sf::ConvexShape]==])
set_tests_properties( [==[[Graphics] sf::ConvexShape]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Graphics] sf::CoordinateType]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-graphics.exe [==[--test-case=[Graphics] sf::CoordinateType]==])
set_tests_properties( [==[[Graphics] sf::CoordinateType]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Graphics] sf::Font]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-graphics.exe [==[--test-case=[Graphics] sf::Font]==])
set_tests_properties( [==[[Graphics] sf::Font]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Graphics] sf::Glsl]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-graphics.exe [==[--test-case=[Graphics] sf::Glsl]==])
set_tests_properties( [==[[Graphics] sf::Glsl]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Graphics] sf::Glyph]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-graphics.exe [==[--test-case=[Graphics] sf::Glyph]==])
set_tests_properties( [==[[Graphics] sf::Glyph]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Graphics] sf::Image]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-graphics.exe [==[--test-case=[Graphics] sf::Image]==])
set_tests_properties( [==[[Graphics] sf::Image]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Graphics] sf::RectangleShape]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-graphics.exe [==[--test-case=[Graphics] sf::RectangleShape]==])
set_tests_properties( [==[[Graphics] sf::RectangleShape]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Graphics] Render Tests]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-graphics.exe [==[--test-case=[Graphics] Render Tests]==])
set_tests_properties( [==[[Graphics] Render Tests]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Graphics] sf::RenderStates]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-graphics.exe [==[--test-case=[Graphics] sf::RenderStates]==])
set_tests_properties( [==[[Graphics] sf::RenderStates]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Graphics] sf::RenderTarget]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-graphics.exe [==[--test-case=[Graphics] sf::RenderTarget]==])
set_tests_properties( [==[[Graphics] sf::RenderTarget]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Graphics] sf::RenderTexture]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-graphics.exe [==[--test-case=[Graphics] sf::RenderTexture]==])
set_tests_properties( [==[[Graphics] sf::RenderTexture]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Graphics] sf::RenderWindow]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-graphics.exe [==[--test-case=[Graphics] sf::RenderWindow]==])
set_tests_properties( [==[[Graphics] sf::RenderWindow]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Graphics] sf::Shader]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-graphics.exe [==[--test-case=[Graphics] sf::Shader]==])
set_tests_properties( [==[[Graphics] sf::Shader]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Graphics] sf::Shape]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-graphics.exe [==[--test-case=[Graphics] sf::Shape]==])
set_tests_properties( [==[[Graphics] sf::Shape]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Graphics] sf::Sprite]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-graphics.exe [==[--test-case=[Graphics] sf::Sprite]==])
set_tests_properties( [==[[Graphics] sf::Sprite]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Graphics] sf::StencilMode]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-graphics.exe [==[--test-case=[Graphics] sf::StencilMode]==])
set_tests_properties( [==[[Graphics] sf::StencilMode]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Graphics] sf::Text]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-graphics.exe [==[--test-case=[Graphics] sf::Text]==])
set_tests_properties( [==[[Graphics] sf::Text]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Graphics] sf::Texture]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-graphics.exe [==[--test-case=[Graphics] sf::Texture]==])
set_tests_properties( [==[[Graphics] sf::Texture]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Graphics] sf::Transform]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-graphics.exe [==[--test-case=[Graphics] sf::Transform]==])
set_tests_properties( [==[[Graphics] sf::Transform]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Graphics] sf::Transformable]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-graphics.exe [==[--test-case=[Graphics] sf::Transformable]==])
set_tests_properties( [==[[Graphics] sf::Transformable]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Graphics] sf::Vertex]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-graphics.exe [==[--test-case=[Graphics] sf::Vertex]==])
set_tests_properties( [==[[Graphics] sf::Vertex]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Graphics] sf::VertexBuffer[.display]]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-graphics.exe [==[--test-case=[Graphics] sf::VertexBuffer[.display]]==])
set_tests_properties( [==[[Graphics] sf::VertexBuffer[.display]]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Graphics] sf::View]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-graphics.exe [==[--test-case=[Graphics] sf::View]==])
set_tests_properties( [==[[Graphics] sf::View]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
set( test-sfml-graphics_TESTS [==[[Graphics] sf::BlendMode]==] [==[[Graphics] sf::CircleShape]==] [==[[Graphics] sf::Color]==] [==[[Graphics] sf::ConvexShape]==] [==[[Graphics] sf::CoordinateType]==] [==[[Graphics] sf::Font]==] [==[[Graphics] sf::Glsl]==] [==[[Graphics] sf::Glyph]==] [==[[Graphics] sf::Image]==] [==[[Graphics] sf::RectangleShape]==] [==[[Graphics] Render Tests]==] [==[[Graphics] sf::RenderStates]==] [==[[Graphics] sf::RenderTarget]==] [==[[Graphics] sf::RenderTexture]==] [==[[Graphics] sf::RenderWindow]==] [==[[Graphics] sf::Shader]==] [==[[Graphics] sf::Shape]==] [==[[Graphics] sf::Sprite]==] [==[[Graphics] sf::StencilMode]==] [==[[Graphics] sf::Text]==] [==[[Graphics] sf::Texture]==] [==[[Graphics] sf::Transform]==] [==[[Graphics] sf::Transformable]==] [==[[Graphics] sf::Vertex]==] [==[[Graphics] sf::VertexBuffer[.display]]==] [==[[Graphics] sf::View]==])
