if(EXISTS "C:/OHWorkspace/SFML/buildrel/test/test-sfml-window_tests-b858cb2.cmake")
  include("C:/OHWorkspace/SFML/buildrel/test/test-sfml-window_tests-b858cb2.cmake")
else()
  add_test(test-sfml-window_NOT_BUILT-b858cb2 test-sfml-window_NOT_BUILT-b858cb2)
endif()
