add_test( [==[[System] sf::Angle]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-system.exe [==[--test-case=[System] sf::Angle]==])
set_tests_properties( [==[[System] sf::Angle]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[System] sf::Clock]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-system.exe [==[--test-case=[System] sf::Clock]==])
set_tests_properties( [==[[System] sf::Clock]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[System] SFML/Config.hpp]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-system.exe [==[--test-case=[System] SFML/Config.hpp]==])
set_tests_properties( [==[[System] SFML/Config.hpp]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[System] sf::err]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-system.exe [==[--test-case=[System] sf::err]==])
set_tests_properties( [==[[System] sf::err]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[System] sf::FileInputStream]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-system.exe [==[--test-case=[System] sf::FileInputStream]==])
set_tests_properties( [==[[System] sf::FileInputStream]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[System] sf::MemoryInputStream]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-system.exe [==[--test-case=[System] sf::MemoryInputStream]==])
set_tests_properties( [==[[System] sf::MemoryInputStream]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Graphics] sf::Rect<int>]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-system.exe [==[--test-case=[Graphics] sf::Rect<int>]==])
set_tests_properties( [==[[Graphics] sf::Rect<int>]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Graphics] sf::Rect<float>]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-system.exe [==[--test-case=[Graphics] sf::Rect<float>]==])
set_tests_properties( [==[[Graphics] sf::Rect<float>]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[System] sf::sleep]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-system.exe [==[--test-case=[System] sf::sleep]==])
set_tests_properties( [==[[System] sf::sleep]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[System] sf::String]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-system.exe [==[--test-case=[System] sf::String]==])
set_tests_properties( [==[[System] sf::String]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[System] sf::Time]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-system.exe [==[--test-case=[System] sf::Time]==])
set_tests_properties( [==[[System] sf::Time]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[System] sf::Vector2<int>]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-system.exe [==[--test-case=[System] sf::Vector2<int>]==])
set_tests_properties( [==[[System] sf::Vector2<int>]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[System] sf::Vector2<float>]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-system.exe [==[--test-case=[System] sf::Vector2<float>]==])
set_tests_properties( [==[[System] sf::Vector2<float>]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[System] sf::Vector3<int>]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-system.exe [==[--test-case=[System] sf::Vector3<int>]==])
set_tests_properties( [==[[System] sf::Vector3<int>]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[System] sf::Vector3<float>]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-system.exe [==[--test-case=[System] sf::Vector3<float>]==])
set_tests_properties( [==[[System] sf::Vector3<float>]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
set( test-sfml-system_TESTS [==[[System] sf::Angle]==] [==[[System] sf::Clock]==] [==[[System] SFML/Config.hpp]==] [==[[System] sf::err]==] [==[[System] sf::FileInputStream]==] [==[[System] sf::MemoryInputStream]==] [==[[Graphics] sf::Rect<int>]==] [==[[Graphics] sf::Rect<float>]==] [==[[System] sf::sleep]==] [==[[System] sf::String]==] [==[[System] sf::Time]==] [==[[System] sf::Vector2<int>]==] [==[[System] sf::Vector2<float>]==] [==[[System] sf::Vector3<int>]==] [==[[System] sf::Vector3<float>]==])
