add_test( [==[[Network] sf::Ftp]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-network.exe [==[--test-case=[Network] sf::Ftp]==])
set_tests_properties( [==[[Network] sf::Ftp]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Network] sf::Http]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-network.exe [==[--test-case=[Network] sf::Http]==])
set_tests_properties( [==[[Network] sf::Http]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Network] sf::IpAddress]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-network.exe [==[--test-case=[Network] sf::IpAddress]==])
set_tests_properties( [==[[Network] sf::IpAddress]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Network] sf::Packet]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-network.exe [==[--test-case=[Network] sf::Packet]==])
set_tests_properties( [==[[Network] sf::Packet]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Network] sf::Socket]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-network.exe [==[--test-case=[Network] sf::Socket]==])
set_tests_properties( [==[[Network] sf::Socket]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Network] sf::SocketSelector]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-network.exe [==[--test-case=[Network] sf::SocketSelector]==])
set_tests_properties( [==[[Network] sf::SocketSelector]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Network] sf::TcpListener]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-network.exe [==[--test-case=[Network] sf::TcpListener]==])
set_tests_properties( [==[[Network] sf::TcpListener]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Network] sf::TcpSocket]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-network.exe [==[--test-case=[Network] sf::TcpSocket]==])
set_tests_properties( [==[[Network] sf::TcpSocket]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
add_test( [==[[Network] sf::UdpSocket]==] C:/OHWorkspace/SFML/buildrel/bin/test-sfml-network.exe [==[--test-case=[Network] sf::UdpSocket]==])
set_tests_properties( [==[[Network] sf::UdpSocket]==] PROPERTIES WORKING_DIRECTORY C:/OHWorkspace/SFML/test LABELS)
set( test-sfml-network_TESTS [==[[Network] sf::Ftp]==] [==[[Network] sf::Http]==] [==[[Network] sf::IpAddress]==] [==[[Network] sf::Packet]==] [==[[Network] sf::Socket]==] [==[[Network] sf::SocketSelector]==] [==[[Network] sf::TcpListener]==] [==[[Network] sf::TcpSocket]==] [==[[Network] sf::UdpSocket]==])
