// LICENSE AND COPYRIGHT (C) INFORMATION
// https://github.com/vittorioromeo/VRSFML/blob/master/license.md


////////////////////////////////////////////////////////////
// Headers
////////////////////////////////////////////////////////////
#include "SFML/Network/SocketSelector.hpp"

#include "SFML/Network/Socket.hpp"
#include "SFML/Network/SocketHandle.hpp"
#include "SFML/Network/SocketImpl.hpp"

#include "SFML/System/Err.hpp"
#include "SFML/System/Time.hpp"

#include "SFML/Base/MinMax.hpp"
#include "SFML/Base/SizeT.hpp"
#include "SFML/Base/Span.hpp"
#include "SFML/Base/Vector.hpp"

#ifdef _MSC_VER
    #pragma warning(disable : 4127) // "conditional expression is constant" generated by the FD_SET macro
#endif


namespace sf
{
////////////////////////////////////////////////////////////
SocketSelector::~SocketSelector() = default;


////////////////////////////////////////////////////////////
// Per-socket registration record. Needed to rebuild the
// ready lists in `wait()` -- `select()` only reports by
// handle, so we have to remember which `Socket*` each handle
// maps back to.
////////////////////////////////////////////////////////////
namespace
{
struct SocketEntry
{
    Socket*      socket{};
    SocketHandle handle{};
    void*        userData{};
    bool         forReceive = false;
    bool         forSend    = false;
};

} // namespace


////////////////////////////////////////////////////////////
struct SocketSelector::Impl
{
    priv::FDSet allSocketsRead;  //!< Sockets registered via `add`
    priv::FDSet allSocketsWrite; //!< Sockets registered via `addForSend`
    priv::FDSet socketsReadable; //!< Populated by `wait()` -- sockets reported readable
    priv::FDSet socketsWritable; //!< Populated by `wait()` -- sockets reported writable
    priv::FDSet exceptScratch;   //!< Zeroed scratch -- `priv::SocketImpl::select` requires non-null `exceptfds`

    int maxSocket{};

    base::Vector<SocketEntry>                entries;
    base::Vector<SocketSelector::ReadyEntry> readyReceiveList;
    base::Vector<SocketSelector::ReadyEntry> readySendList;
};


////////////////////////////////////////////////////////////
SocketSelector::SocketSelector()
{
    clear();
}


////////////////////////////////////////////////////////////
SocketSelector::SocketSelector(const SocketSelector&)                = default;
SocketSelector& SocketSelector::operator=(const SocketSelector&)     = default;
SocketSelector::SocketSelector(SocketSelector&&) noexcept            = default;
SocketSelector& SocketSelector::operator=(SocketSelector&&) noexcept = default;


////////////////////////////////////////////////////////////
namespace
{
////////////////////////////////////////////////////////////
// Find an existing entry by Socket identity (pointer).
[[nodiscard]] SocketEntry* findEntry(base::Vector<SocketEntry>& entries, const Socket* socket)
{
    for (SocketEntry& e : entries)
        if (e.socket == socket)
            return &e;

    return nullptr;
}


////////////////////////////////////////////////////////////
// Remove an element from a Vector<ReadyEntry> by socket-pointer-equality, if present.
void eraseFromList(base::Vector<SocketSelector::ReadyEntry>& list, const Socket* socket)
{
    for (base::SizeT i = 0; i < list.size(); ++i)
        if (list[i].socket == socket)
        {
            list.erase(list.begin() + static_cast<decltype(list.end() - list.begin())>(i));
            return;
        }
}

} // namespace


////////////////////////////////////////////////////////////
bool SocketSelector::addWith(Impl& impl, Socket& socket, void* const userData, const bool forReceive, const bool forSend)
{
    const SocketHandle handle = socket.getNativeHandle();

    if (handle == priv::SocketImpl::invalidSocket())
    {
        priv::err() << "Attempted to add invalid socket to socket selector";
        return false;
    }

    SocketEntry* existing = findEntry(impl.entries, &socket);

    if (existing == nullptr)
    {
#if defined(SFML_SYSTEM_WINDOWS)
        if (static_cast<int>(impl.entries.size()) >= priv::SocketImpl::getFDSetSize())
        {
            priv::err() << "The socket can't be added to the selector because the selector is full. This is a "
                           "limitation of your operating system's FD_SETSIZE setting.";
            return false;
        }
#else
        if (handle >= priv::SocketImpl::getFDSetSize())
        {
            priv::err() << "The socket can't be added to the selector because its ID is too high. This is a limitation "
                           "of your operating system's FD_SETSIZE setting.";
            return false;
        }

        impl.maxSocket = base::max(impl.maxSocket, handle);
#endif

        impl.entries.emplaceBack(SocketEntry{&socket, handle, userData, forReceive, forSend});
    }
    else
    {
        // Preserve whichever flag was set before; just OR in the new one.
        existing->forReceive = existing->forReceive || forReceive;
        existing->forSend    = existing->forSend || forSend;
        // userData: each call replaces the stored value.
        existing->userData = userData;
    }

    if (forReceive)
        priv::SocketImpl::fdSet(handle, impl.allSocketsRead);

    if (forSend)
        priv::SocketImpl::fdSet(handle, impl.allSocketsWrite);

    return true;
}


////////////////////////////////////////////////////////////
bool SocketSelector::add(Socket& socket, void* const userData)
{
    return addWith(*m_impl, socket, userData, /* forReceive */ true, /* forSend */ false);
}


////////////////////////////////////////////////////////////
bool SocketSelector::addForSend(Socket& socket, void* const userData)
{
    return addWith(*m_impl, socket, userData, /* forReceive */ false, /* forSend */ true);
}


////////////////////////////////////////////////////////////
bool SocketSelector::remove(const Socket& socket)
{
    const SocketHandle handle = socket.getNativeHandle();

    if (handle == priv::SocketImpl::invalidSocket())
    {
        priv::err() << "Attempted to remove invalid socket from socket selector";
        return false;
    }

#if !defined(SFML_SYSTEM_WINDOWS)
    if (handle >= priv::SocketImpl::getFDSetSize())
    {
        priv::err() << "The socket can't be removed from the selector because its ID is too high. This is a "
                       "limitation of your operating system's FD_SETSIZE setting.";
        return false;
    }
#endif

    // Clear registration bits.
    priv::SocketImpl::fdClear(handle, m_impl->allSocketsRead);
    priv::SocketImpl::fdClear(handle, m_impl->allSocketsWrite);

    // Clear stale "ready" bits so `isReady` / `isReadyToSend` return false immediately.
    priv::SocketImpl::fdClear(handle, m_impl->socketsReadable);
    priv::SocketImpl::fdClear(handle, m_impl->socketsWritable);

    // Drop the entry if we have one.
    for (base::SizeT i = 0; i < m_impl->entries.size(); ++i)
        if (m_impl->entries[i].socket == &socket)
        {
            m_impl->entries.eraseAt(i);
            break;
        }

    // Keep the cached ready lists consistent.
    eraseFromList(m_impl->readyReceiveList, &socket);
    eraseFromList(m_impl->readySendList, &socket);

    return true;
}


////////////////////////////////////////////////////////////
void SocketSelector::clear()
{
    priv::SocketImpl::fdZero(m_impl->allSocketsRead);
    priv::SocketImpl::fdZero(m_impl->allSocketsWrite);
    priv::SocketImpl::fdZero(m_impl->socketsReadable);
    priv::SocketImpl::fdZero(m_impl->socketsWritable);
    priv::SocketImpl::fdZero(m_impl->exceptScratch);

    m_impl->maxSocket = 0;

    m_impl->entries.clear();
    m_impl->readyReceiveList.clear();
    m_impl->readySendList.clear();
}


////////////////////////////////////////////////////////////
bool SocketSelector::wait(const Time timeout)
{
    // `select()` overwrites the fd_sets it's given, so we hand it copies.
    m_impl->socketsReadable = m_impl->allSocketsRead;
    m_impl->socketsWritable = m_impl->allSocketsWrite;
    priv::SocketImpl::fdZero(m_impl->exceptScratch);

    const int count = priv::SocketImpl::select(m_impl->maxSocket + 1,
                                               &m_impl->socketsReadable,
                                               &m_impl->socketsWritable,
                                               &m_impl->exceptScratch,
                                               timeout.asMicroseconds());

    // Always rebuild the ready lists from scratch -- they are valid only until the next `wait`.
    m_impl->readyReceiveList.clear();
    m_impl->readySendList.clear();

    if (count > 0)
        for (const auto& e : m_impl->entries)
        {
            if (e.forReceive && priv::SocketImpl::fdIsSet(e.handle, m_impl->socketsReadable))
                m_impl->readyReceiveList.emplaceBack(ReadyEntry{e.socket, e.userData});

            if (e.forSend && priv::SocketImpl::fdIsSet(e.handle, m_impl->socketsWritable))
                m_impl->readySendList.emplaceBack(ReadyEntry{e.socket, e.userData});
        }

    return count > 0;
}


////////////////////////////////////////////////////////////
base::Span<const SocketSelector::ReadyEntry> SocketSelector::getReadyToReceive() const
{
    return {m_impl->readyReceiveList.data(), m_impl->readyReceiveList.size()};
}


////////////////////////////////////////////////////////////
base::Span<const SocketSelector::ReadyEntry> SocketSelector::getReadyToSend() const
{
    return {m_impl->readySendList.data(), m_impl->readySendList.size()};
}


////////////////////////////////////////////////////////////
namespace
{
[[nodiscard]] bool isHandleInSet(SocketHandle handle, const priv::FDSet& set)
{
    if (handle == priv::SocketImpl::invalidSocket())
        return false;

#if !defined(SFML_SYSTEM_WINDOWS)
    if (handle >= priv::SocketImpl::getFDSetSize())
        return false;
#endif

    return priv::SocketImpl::fdIsSet(handle, set);
}
} // namespace


////////////////////////////////////////////////////////////
bool SocketSelector::isReady(const Socket& socket) const
{
    return isHandleInSet(socket.getNativeHandle(), m_impl->socketsReadable);
}


////////////////////////////////////////////////////////////
bool SocketSelector::isReadyToSend(const Socket& socket) const
{
    return isHandleInSet(socket.getNativeHandle(), m_impl->socketsWritable);
}

} // namespace sf
