#include "Tst/Tst.hpp"

#include "Zancle/Config.hpp"

TEST_CASE("[System] SFML/Config.hpp")
{
    SECTION("Version macros")
    {
        STATIC_CHECK(ZA_VERSION_MAJOR == EXPECTED_SFML_VERSION_MAJOR);
        STATIC_CHECK(ZA_VERSION_MINOR == EXPECTED_SFML_VERSION_MINOR);
        STATIC_CHECK(ZA_VERSION_PATCH == EXPECTED_SFML_VERSION_PATCH);
        STATIC_CHECK(ZA_VERSION_IS_RELEASE == EXPECTED_SFML_VERSION_IS_RELEASE);
    }
}
